Specify Jacoco version to 0.8.6
Jacoco needs to be updated because it does not fully support inlined
Kotlin code and Sonar skip files where line number is out of range:

```
Cannot import coverage information for file 'publisher-sdk/src/main/java/com/criteo/publisher/context/ContextProvider.kt', coverage data is invalid. Error: {}
java.lang.IllegalStateException: Line 186 is out of range in the file publisher-sdk/src/main/java/com/criteo/publisher/context/ContextProvider.kt (lines: 185)
```

This is related to https://github.com/jacoco/jacoco/issues/763. Using
Jacoco >= 0.8.3 should fix this issue.